import { Injectable } from '@angular/core';
import { News } from '../models/news';

@Injectable()
export class NewsService {
  getNews(): News[] {
    return [
      { id: 1, title: 'Title 1', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 1, imgUrl: '' },
      { id: 2, title: 'Title 2', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 2, imgUrl: '' },
      { id: 3, title: 'Title 3', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 3, imgUrl: '' },
      { id: 4, title: 'Title 4', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 4, imgUrl: '' },
      { id: 5, title: 'Title 5', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 5, imgUrl: '' },
      { id: 6, title: 'Title 6', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 6, imgUrl: '' },
      { id: 7, title: 'Title 7', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 7, imgUrl: '' },
      { id: 8, title: 'Title 8', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 8, imgUrl: '' },
      { id: 9, title: 'Title 9', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 9, imgUrl: '' },
      { id: 10, title: 'Title 10', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 10, imgUrl: '' }
    ];
  }

  getTopNews(): News[] {
    return [
      { id: 1, title: 'Title 1', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 1, imgUrl: '' },
      { id: 2, title: 'Title 2', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 2, imgUrl: '' },
      { id: 3, title: 'Title 3', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 3, imgUrl: '' },
      { id: 4, title: 'Title 4', text: 'Czy nietypowy trening zastosowany dziś przez Antonio Conte pomoże graczom Chelsea w lepszej dyspozycji na sobotni, finałowy mecz Pucharu Anglii z Manchesterem United? \'Zabawy\' z tzw. szwajcarskimi piłkami czy ćwiczenia siłowe z uprzężą - to inne niż treningi niż dotychczas, jakie znali zawodnicy Chelsea.Poniżej obrazki', author: 'Mateusz Hernik', addDate: Date.now(), commentsCount: 4, imgUrl: '' }
    ];
  }
} 
